apiVersion : v1

kind: ConfigMap

metadata:
  name: rag-config
  namespace: rag-ai

data:
  LLM_MODEL: "llama3.2:3b"

  EMBEDDING_MODEL: "nomic-embed-text"

  OLLAMA_BASE_URL: "http://ollama-service:11434"

  CHROMA_PATH: "/app/chroma_db"

  UPLOAD_FOLDER: "/app/uploads"

  DOCUMENT_FOLDER: "/app/documents"

  LOG_LEVEL: "INFO"