apiVersion: v1
kind: Service

metadata:
  name: rag-api-service
  namespace: rag-ai

spec:

  selector:
    app: rag-api

  type: NodePort

  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080